import { StyleSheet } from 'react-native';
import { colors } from './colors';

// ─── StatusBadge ────────────────────────────────────────────────────────────
export const statusBadgeStyles = StyleSheet.create({
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  small: {
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  text: {
    fontSize: 12,
    fontWeight: '700',
  },
  smallText: {
    fontSize: 11,
    fontWeight: '700',
  },
});

// ─── BottomTabBar ────────────────────────────────────────────────────────────
export const bottomTabBarStyles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    backgroundColor: colors.tabBarBg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 10,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    gap: 3,
  },
  label: {
    fontSize: 10,
    color: colors.tabInactive,
    fontWeight: '500',
  },
  activeLabel: {
    color: colors.tabActive,
  },
});

// ─── HomeScreen ──────────────────────────────────────────────────────────────
export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    gap: 10,
  },
  iconBtn: { padding: 4 },
  headerText: { flex: 1 },
  greeting: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  subGreeting: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
  },
  scroll: {
    paddingBottom: 8,
  },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 10,
    marginTop: 4,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  statNum: {
    color: colors.textPrimary,
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 34,
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 15,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  viewAll: {
    color: colors.tabActive,
    fontSize: 13,
    fontWeight: '500',
  },
  missionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  animalPhoto: {
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  missionInfo: {
    flex: 1,
    gap: 5,
  },
  animalName: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  locationText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  timeText: {
    color: colors.textMuted,
    fontSize: 11,
    marginTop: 1,
  },
});

// ─── NewMissionScreen ────────────────────────────────────────────────────────
export const newMissionStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backBtn: {
    padding: 4,
    marginRight: 4,
  },
  title: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  saveText: {
    color: colors.tabActive,
    fontSize: 15,
    fontWeight: '600',
    padding: 4,
  },
  scroll: {
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  fieldGroup: {
    marginBottom: 16,
  },
  fieldLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 7,
  },
  selectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  selectText: {
    flex: 1,
    color: colors.inputText,
    fontSize: 14,
    fontWeight: '500',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 14,
  },
  textInput: {
    flex: 1,
    color: colors.inputText,
    fontSize: 14,
    paddingVertical: 14,
  },
  inputIcon: {
    marginLeft: 8,
  },
  textArea: {
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: colors.inputText,
    fontSize: 14,
    minHeight: 100,
  },
  photosRow: {
    flexDirection: 'row',
    gap: 10,
  },
  photoThumb: {
    width: 88,
    height: 88,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoEmoji: {
    fontSize: 38,
  },
  addPhotoBtn: {
    width: 88,
    height: 88,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.inputBg,
  },
  publishBtn: {
    backgroundColor: colors.primaryBtn,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  publishText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  dropdownBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  dropdownItem: {
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.divider,
  },
  dropdownText: {
    color: colors.inputText,
    fontSize: 15,
  },
});

// ─── MissionDetailsScreen ────────────────────────────────────────────────────
export const missionDetailsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  iconBtn: { padding: 4 },
  title: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  scroll: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  missionId: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  heroPhoto: {
    width: '100%',
    height: 210,
    backgroundColor: '#d8e8d0',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  heroEmoji: {
    fontSize: 95,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  animalName: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: '700',
  },
  locationsCard: {
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 14,
    marginBottom: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  locationText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  statsRow: {
    flexDirection: 'row',
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    marginBottom: 5,
  },
  statValue: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: '700',
  },
  statDivider: {
    width: 1,
    height: 38,
    backgroundColor: colors.border,
  },
  detailsHeader: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 12,
  },
  detailItem: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  detailIcon: {
    marginTop: 2,
    flexShrink: 0,
  },
  detailText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  acceptBtn: {
    backgroundColor: colors.primaryBtn,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 10,
  },
  acceptText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  declineBtn: {
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.dangerBorder,
  },
  declineText: {
    color: colors.danger,
    fontSize: 16,
    fontWeight: '600',
  },
  mapSectionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
  },
  mapWrapper: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 4,
  },
  mapBg: {
    height: 200,
    backgroundColor: colors.mapBg,
    position: 'relative',
  },
  mapRoad: {
    position: 'absolute',
    backgroundColor: colors.mapRoad,
  },
  mapRouteH: {
    position: 'absolute',
    bottom: '30%',
    left: '20%',
    width: '38%',
    height: 4,
    backgroundColor: colors.mapRoute,
    borderRadius: 2,
  },
  mapRouteV: {
    position: 'absolute',
    bottom: '30%',
    left: '58%',
    width: 4,
    height: '58%',
    backgroundColor: colors.mapRoute,
    borderRadius: 2,
  },
  volunteerRing: {
    position: 'absolute',
    bottom: '26%',
    left: '17%',
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(25,118,210,0.20)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  volunteerDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.mapOrigin,
    borderWidth: 2,
    borderColor: '#fff',
  },
  volunteerLabel: {
    position: 'absolute',
    bottom: '18%',
    left: '15%',
    fontSize: 10,
    fontWeight: '600',
    color: colors.mapOrigin,
  },
  animalPinWrap: {
    position: 'absolute',
    top: '8%',
    left: '55%',
    alignItems: 'center',
  },
  animalPinHead: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.mapDest,
    borderWidth: 2,
    borderColor: '#fff',
  },
  animalPinTail: {
    width: 3,
    height: 8,
    backgroundColor: colors.mapDest,
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
  },
  animalLabel: {
    position: 'absolute',
    top: '38%',
    left: '52%',
    fontSize: 10,
    fontWeight: '600',
    color: colors.mapDest,
  },
  mapBar: {
    flexDirection: 'row',
    backgroundColor: colors.cardBg,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  mapBarItem: {
    flex: 1,
    alignItems: 'center',
    gap: 3,
  },
  mapBarLabel: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  mapBarValue: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  mapBarDivider: {
    width: 1,
    height: 36,
    backgroundColor: colors.border,
  },
  locationDividerRow: {
    paddingLeft: 6,
    paddingVertical: 4,
  },
  locationDividerLine: {
    width: 1,
    height: 14,
    backgroundColor: colors.border,
    marginLeft: 1,
  },
});

// ─── MissionTrackingScreen ───────────────────────────────────────────────────
export const missionTrackingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  iconBtn: { padding: 4 },
  title: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  scroll: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  missionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    marginBottom: 22,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardPhotoWrap: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: '#d8e4cc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardEmoji: { fontSize: 28 },
  cardInfo: { flex: 1 },
  cardAnimal: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  cardId: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 3,
  },
  timeline: {
    marginBottom: 20,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    minHeight: 58,
  },
  dotColumn: {
    width: 26,
    alignItems: 'center',
    marginRight: 14,
  },
  dot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  dotActive: {
    borderWidth: 3,
    borderColor: colors.timelineActive,
    backgroundColor: colors.background,
  },
  dotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.timelineActive,
  },
  line: {
    width: 2,
    flex: 1,
    minHeight: 30,
    marginTop: 2,
  },
  stepContent: {
    flex: 1,
    paddingTop: 1,
  },
  stepLabel: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  stepSub: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 3,
  },
  stepTime: {
    color: colors.textSecondary,
    fontSize: 12,
    paddingTop: 2,
  },
  stepMuted: {
    color: colors.textMuted,
  },
  mapWrapper: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  mapBg: {
    height: 200,
    backgroundColor: colors.mapBg,
    position: 'relative',
  },
  road: {
    position: 'absolute',
    backgroundColor: colors.mapRoad,
  },
  routeH: {
    position: 'absolute',
    bottom: '38%',
    left: '22%',
    width: '35%',
    height: 4,
    backgroundColor: colors.mapRoute,
    borderRadius: 2,
  },
  routeV: {
    position: 'absolute',
    bottom: '38%',
    left: '57%',
    width: 4,
    height: '52%',
    backgroundColor: colors.mapRoute,
    borderRadius: 2,
  },
  originRing: {
    position: 'absolute',
    bottom: '36%',
    left: '19%',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(25,118,210,0.20)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  originDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.mapOrigin,
    borderWidth: 2,
    borderColor: '#fff',
  },
  destPinWrap: {
    position: 'absolute',
    top: '10%',
    left: '54%',
    alignItems: 'center',
  },
  destPinHead: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.mapDest,
    borderWidth: 2,
    borderColor: '#fff',
  },
  destPinTail: {
    width: 3,
    height: 8,
    backgroundColor: colors.mapDest,
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
  },
  etaBar: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 16,
    alignItems: 'center',
    backgroundColor: colors.cardBg,
  },
  etaItem: {
    flex: 1,
    alignItems: 'center',
  },
  etaLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    marginBottom: 4,
  },
  etaValue: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '700',
  },
  etaDivider: {
    width: 1,
    height: 38,
    backgroundColor: colors.border,
  },
  deliverBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primaryBtn,
    borderRadius: 12,
    paddingVertical: 16,
    marginTop: 20,
  },
  deliverBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
});

// ─── MissionCompletedScreen ──────────────────────────────────────────────────
export const missionCompletedStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  iconBtn: { padding: 4 },
  title: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  scroll: {
    paddingHorizontal: 16,
    paddingTop: 28,
  },
  successSection: {
    alignItems: 'center',
    marginBottom: 26,
  },
  checkCircle: {
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: colors.primaryBtn,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  completedTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  completedSub: {
    color: colors.textSecondary,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 21,
  },
  missionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardPhotoWrap: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: '#d8e4cc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardEmoji: { fontSize: 28 },
  cardInfo: { flex: 1 },
  cardAnimal: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  cardId: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 3,
  },
  summaryHeader: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 12,
  },
  summaryCard: {
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  summaryRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  summaryLabel: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  summaryValue: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  historyBtn: {
    backgroundColor: colors.primaryBtn,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  historyText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
});

// ─── VolunteersScreen ────────────────────────────────────────────────────────
export const volunteersStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  title: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  iconBtn: { padding: 4 },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 10,
    marginVertical: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  statNum: {
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 28,
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 3,
  },
  filterRow: {
    paddingHorizontal: 16,
    gap: 8,
    paddingBottom: 14,
  },
  filterTab: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: colors.cardBg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterTabActive: {
    backgroundColor: colors.primaryBtn,
    borderColor: colors.primaryBtn,
  },
  filterText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '500',
  },
  filterTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  scroll: {
    paddingHorizontal: 16,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  statusDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#fff',
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
  info: {
    flex: 1,
    gap: 4,
  },
  name: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  sub: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  right: {
    alignItems: 'flex-end',
    gap: 4,
  },
  statusLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  missionsCount: {
    color: colors.textMuted,
    fontSize: 11,
  },
  callBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.tabActive,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
});

// ─── AdminScreen ─────────────────────────────────────────────────────────────
export const adminStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  iconBtn: { padding: 4 },
  title: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  scroll: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  welcomeCard: {
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  welcomeTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  welcomeSub: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 3,
  },
  roleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.onTheWayBg,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  roleText: {
    color: colors.tabActive,
    fontSize: 12,
    fontWeight: '600',
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    marginTop: 4,
  },
  pendingBadge: {
    backgroundColor: colors.urgent,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  overviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  overviewCard: {
    width: '47%',
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 16,
    gap: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  overviewNum: {
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 32,
  },
  overviewLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
  },
  actionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  actionCard: {
    width: '47%',
    borderRadius: 12,
    padding: 18,
    gap: 10,
    alignItems: 'flex-start',
  },
  actionLabel: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  pendingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  animalPhoto: {
    width: 50,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  animalEmoji: { fontSize: 24 },
  pendingInfo: {
    flex: 1,
    gap: 4,
  },
  animalName: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  subText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  sinceText: {
    color: colors.textMuted,
    fontSize: 11,
  },
  pendingRight: {
    alignItems: 'flex-end',
    gap: 8,
  },
  assignBtn: {
    backgroundColor: colors.primaryBtn,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
  },
  assignText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  activityCard: {
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 12,
  },
  activityRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  activityIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  activityInfo: {
    flex: 1,
  },
  activityText: {
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 18,
  },
  activityTime: {
    color: colors.textMuted,
    fontSize: 11,
    marginTop: 2,
  },
});

// ─── LoginScreen ─────────────────────────────────────────────────────────────
export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  logoSection: {
    alignItems: 'center',
    paddingTop: 52,
    paddingBottom: 36,
  },
  logoCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.primaryBtn,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  logoEmoji: {
    fontSize: 40,
  },
  appName: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  appSub: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 3,
  },
  toggleRow: {
    flexDirection: 'row',
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    padding: 4,
    marginBottom: 28,
  },
  toggleBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  toggleBtnActive: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  toggleText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  toggleTextActive: {
    color: colors.textPrimary,
  },
  errorText: {
    color: colors.danger,
    fontSize: 13,
    marginBottom: 14,
    textAlign: 'center',
  },
  formTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  formSub: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 24,
  },
  fieldGroup: {
    marginBottom: 14,
  },
  fieldLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 7,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 14,
  },
  inputIcon: {
    marginRight: 8,
  },
  textInput: {
    flex: 1,
    color: colors.inputText,
    fontSize: 14,
    paddingVertical: 14,
  },
  eyeBtn: {
    padding: 4,
  },
  primaryBtn: {
    backgroundColor: colors.primaryBtn,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  primaryBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  registerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  registerHint: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  registerLink: {
    color: colors.tabActive,
    fontSize: 14,
    fontWeight: '600',
  },
  codeHint: {
    color: colors.textMuted,
    fontSize: 12,
    textAlign: 'center',
    marginTop: 18,
  },
});

// ─── RegisterScreen ───────────────────────────────────────────────────────────
export const registerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  headerRow: {
    paddingTop: 8,
    paddingBottom: 4,
  },
  backIconBtn: {
    padding: 4,
    alignSelf: 'flex-start',
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textPrimary,
    marginTop: 12,
    marginBottom: 4,
  },
  sub: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 28,
  },
  errorText: {
    color: colors.danger,
    fontSize: 13,
    marginBottom: 14,
  },
  fieldGroup: {
    marginBottom: 14,
  },
  fieldLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 7,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 14,
  },
  inputIcon: {
    marginRight: 8,
  },
  textInput: {
    flex: 1,
    color: colors.inputText,
    fontSize: 14,
    paddingVertical: 14,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipActive: {
    backgroundColor: colors.primaryBtn,
    borderColor: colors.primaryBtn,
  },
  chipText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  chipTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  submitBtn: {
    backgroundColor: colors.primaryBtn,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  submitText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  approvalNote: {
    color: colors.textMuted,
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 18,
  },
  successContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  successCircle: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: colors.primaryBtn,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  successTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 12,
    textAlign: 'center',
  },
  successSub: {
    color: colors.textSecondary,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 32,
  },
  backBtn: {
    backgroundColor: colors.primaryBtn,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 40,
    alignItems: 'center',
  },
  backBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
});

// ─── VolunteerHomeScreen ──────────────────────────────────────────────────────
export const volunteerHomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
  },
  iconBtn: {
    padding: 4,
  },
  greeting: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  subGreeting: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
  },
  scroll: {
    paddingBottom: 8,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    paddingHorizontal: 16,
    marginBottom: 10,
    marginTop: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  countBadge: {
    backgroundColor: colors.primaryBtn,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  activeMissionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.onTheWayBg,
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 14,
    gap: 12,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: 'rgba(58,125,48,0.20)',
  },
  activeMissionPhoto: {
    width: 52,
    height: 52,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  activeMissionInfo: {
    flex: 1,
    gap: 5,
  },
  activeMissionAnimal: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  locationText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  missionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  animalPhoto: {
    width: 52,
    height: 52,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  missionInfo: {
    flex: 1,
    gap: 5,
  },
  animalName: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaText: {
    color: colors.textMuted,
    fontSize: 11,
  },
  metaDot: {
    color: colors.textMuted,
    fontSize: 11,
  },
});

// ─── ProfileScreen ────────────────────────────────────────────────────────────
export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  title: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  iconBtn: {
    padding: 4,
  },
  scroll: {
    paddingHorizontal: 16,
    paddingTop: 24,
  },
  avatarSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  avatarCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.primaryBtn,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  avatarInitials: {
    color: '#fff',
    fontSize: 30,
    fontWeight: '700',
  },
  name: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  email: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 12,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.onTheWayBg,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: colors.tabActive,
  },
  statusText: {
    color: colors.tabActive,
    fontSize: 12,
    fontWeight: '600',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statNum: {
    fontSize: 22,
    fontWeight: '800',
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  infoCard: {
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  infoRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  infoIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.onTheWayBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoLabel: {
    color: colors.textMuted,
    fontSize: 11,
    marginBottom: 2,
  },
  infoValue: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '500',
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 24,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.onTheWayBg,
  },
  chipText: {
    color: colors.tabActive,
    fontSize: 13,
    fontWeight: '500',
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 12,
    paddingVertical: 16,
    borderWidth: 1.5,
    borderColor: colors.dangerBorder,
  },
  logoutText: {
    color: colors.danger,
    fontSize: 16,
    fontWeight: '600',
  },
});

export const reportsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  iconBtn: { padding: 4 },
  title: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  scroll: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  filterRow: {
    flexDirection: 'row',
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  filterTab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 10,
  },
  filterTabActive: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  filterText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  filterTextActive: {
    color: colors.textPrimary,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  iconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  chartCard: {
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 24,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 16,
  },
  chartContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 140,
    paddingTop: 10,
  },
  barColumn: {
    alignItems: 'center',
    flex: 1,
  },
  barBackground: {
    width: 14,
    height: 100,
    backgroundColor: colors.inputBg,
    borderRadius: 7,
    justifyContent: 'flex-end',
    marginBottom: 8,
  },
  barFill: {
    width: '100%',
    backgroundColor: colors.primaryBtn,
    borderRadius: 7,
  },
  barLabel: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  reportCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reportIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: 'rgba(58,125,48,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  reportInfo: {
    flex: 1,
  },
  reportTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  reportMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reportDate: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  badge: {
    backgroundColor: colors.inputBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
  },
});

// ─── ReportAnimalScreen ───────────────────────────────────────────────────────
export const reportAnimalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  iconBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 20,
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#eaf4e8',
    borderRadius: 10,
    padding: 12,
    marginBottom: 20,
    gap: 8,
  },
  infoText: {
    flex: 1,
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
  },
  errorText: {
    fontSize: 13,
    color: '#d9534f',
    marginBottom: 12,
    marginTop: -4,
  },
  fieldGroup: {
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  selectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: colors.border,
  },
  selectText: {
    fontSize: 15,
    color: colors.textPrimary,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  inputIcon: {
    marginRight: 8,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    color: colors.textPrimary,
    paddingVertical: 13,
  },
  gpsBtn: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gpsHint: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 6,
  },
  textArea: {
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 15,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 100,
  },
  photosRow: {
    flexDirection: 'row',
    gap: 12,
  },
  addPhotoBtn: {
    flex: 1,
    height: 90,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.inputBg,
    gap: 6,
  },
  addPhotoText: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '500',
  },
  submitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    gap: 8,
    marginTop: 8,
  },
  submitText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  dropdownBox: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 14,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dropdownText: {
    fontSize: 15,
    color: colors.textPrimary,
  },
  successContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingBottom: 60,
  },
  successCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  successSub: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 32,
  },
  newReportBtn: {
    width: '100%',
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  newReportText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  homeBtn: {
    width: '100%',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  homeBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textSecondary,
  },
});
export const sendalertstyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary
  },
  subtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 2
  },
  scroll: {
    paddingHorizontal: 16,
    paddingBottom: 32
  },
  card: {
    backgroundColor: colors.card ?? '#fff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 12
  },
  label: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.textSecondary,
    marginBottom: 6,
    marginTop: 10
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.textPrimary
  },
  textArea: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.textPrimary,
    minHeight: 100,
    textAlignVertical: 'top'
  },
  counter: {
    alignSelf: 'flex-end',
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 4
  },
  pillRow: {
    flexDirection: 'row',
    marginTop: 4
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 8
  },
  pillText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '500'
  },
  pillTextActive: {
    color: colors.card ?? '#fff'
  },
  selectBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 10
  },
  selectText: {
    fontSize: 15,
    color: colors.textPrimary
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'center',
    alignItems: 'center'
  },
  dropdownMenu: {
    width: '80%',
    backgroundColor: colors.card ?? '#fff',
    borderRadius: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: colors.border
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14
  },
  dropdownItemText: {
    fontSize: 15,
    color: colors.textPrimary
  },
  dropdownItemTextActive: {
    fontWeight: '600',
    color: colors.tabActive
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  rowText: {
    fontSize: 15,
    color: colors.textPrimary,
    marginLeft: 10
  },
  sendButton: {
    backgroundColor: colors.tabActive,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8
  },
  sendButtonDisabled: {
    opacity: 0.5
  },
  sendButtonText: {
    color: colors.card ?? '#fff',
    fontSize: 16,
    fontWeight: '600'
  }
  
});